# Generated by Django 3.0.6 on 2020-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('company_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=50, null=True)),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tester_name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'test_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, max_length=36, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('account_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_table',
                'managed': False,
            },
        ),
    ]
